export { default as ButtonComponent } from './Button'
export { default as VuMeterComponent } from './VueMeter'
export { default as Popin } from './popin'
export { default as PopinWeek } from './popinWeek'
export { default as PopinMounth } from './popinMounth'
export { default as PopinYear } from './popinYear'

export { default as DragLeftBtn } from './dragLeftBtn'
export { default as PopinCalculImc } from './popinCaculImc'
export { default as Chart } from './chart'
export { default as CustomTable } from './table'
export { default as Avatar } from './avatar'
