export { default as ButtonComponent } from './Button'
export { default as VuMeterComponent } from './VueMeter'
export { default as PopIn } from './popIn'
export { default as PopInWeek } from './popInWeek'
export { default as PopInMonth } from './popInMonth'
export { default as PopInYear } from './popInYear'

export { default as DragLeftBtn } from './dragLeftBtn'
export { default as PopInCalculImc } from './popInCalculImc'
export { default as Chart } from './chart'
export { default as CustomTable } from './table'
export { default as Avatar } from './avatar'
export { default as Card } from './card'
export { default as BtnBackCircle } from './btnBackCircle'
export { default as InfoImg } from './infoImg'
export { default as PoidsCurent } from './poidsCurent'
export { default as PoidsTarget } from './poidsTarget'
export { default as ResultImc } from './resultImc'
