export { default as Home } from './Home'
export { default as AddProfile } from './AddProfile'
export { default as Profile } from './Profile'
export { default as ImcCalcul } from './ImcCalcul'
export { default as StateInfo } from './StateInfo'
export { default as About } from './about'
